[env]
CARGO_WORKSPACE_DIR = {value = "", relative = true }

# WINDOWS
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static"]

# LINUX
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse4.2"]