/* auto-generated by NAPI-RS */
/* eslint-disable */
/** * Humanize a byte size into a string.
 *
 * @param {number} bytes
 * @returns {string} a string representation of that size in a human-readable format.
 */
export declare function bytes(bytes: number): string

export declare function duration(ms: number, maxUnits?: number | undefined | null, short?: boolean | undefined | null): string
